version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven dependencies..."
      - cd demo-wawawa
      - mvn clean install -DskipTests

artifacts:
  files:
    - target/*.jar
  base-directory: demo-wawawa/target
